Hive insert statements
techfaqs/Tech-FAQs pull request #38
Opened 2017-12-21 14:28 UTC by rukmini-g

2017-12-22 07:23 UTC, animenon requested changes

2017-12-22 07:23 UTC, animenon commented on git/test.txt
> +Testing to raise PR
Delete this file.

2017-12-22 07:23 UTC, animenon commented on hive insert statements
> +''' INSERT INTO TABLE table_name SELECT columnlist FROM secondtable; '''
Make this a `.md` file and add appropriate Headings.

2017-12-22 11:00 UTC, animenon requested changes

2017-12-22 11:00 UTC, animenon commented on hive insert statements.md
> -```INSERT INTO TABLE table_name SELECT columnlist FROM secondtable;```
Please add a header.

2017-12-22 11:00 UTC, animenon commented on hive insert statements.md
> +#*All inserted rows will have the same x and y values. This technique of specifiying all the partition key values is known as static           partitioning.*
Subheadings should use `### ` not `# `

2017-12-22 11:14 UTC, animenon commented on hive insert statements.md
>       ``` set hive.mapred.mode = strict ``` This property set by default in hive-site.xml.*
This doesn't look right, why bold? and why is the line `"This property set ..."` is on the same line?

2017-12-22 11:14 UTC, animenon commented on hive insert statements.md
> +# Hive insert statements
This is right.

2018-01-08 11:24 UTC, closed without merging

2018-01-08 11:24 UTC, rukmini-g commented
closed